services:
    TheMasterNico.RepExtPHPBB.controller:
        class: TheMasterNico\RepExtPHPBB\controller\show_user_rep
        arguments:
            - @controller.helper
            - @template
            - @dbal.conn
            - @request
            - @log
    TheMasterNico.RepExtPHPBB.listener:
        class: TheMasterNico\RepExtPHPBB\event\main_listener
        arguments:
            - @dbal.conn
            - @user
            - @template
            - @request
        tags:
            - { name: event.listener }
